defmodule HeexLint.Grammar.Categories do
  @moduledoc """
  Maps class groups to appearance categories: `color`, `typography`,
  `spacing`, `shape`, `effects` and `motion`. A group with no category is
  layout. Ported from @shadcn/lint's `src/grammar/categories.ts` (MIT).
  """

  @categories ~w(color typography spacing shape effects motion)

  # Every cn class group, mapped to its category; nil is layout.
  @group_category Map.new([
                    {"aspect", nil},
                    {"container", nil},
                    {"container-type", nil},
                    {"container-named", nil},
                    {"contain", nil},
                    {"contain-size", nil},
                    {"contain-layout", nil},
                    {"contain-paint", nil},
                    {"contain-style", nil},
                    {"columns", nil},
                    {"break-after", nil},
                    {"break-before", nil},
                    {"break-inside", nil},
                    {"box-decoration", nil},
                    {"box", nil},
                    {"display", nil},
                    {"sr", nil},
                    {"float", nil},
                    {"clear", nil},
                    {"isolation", nil},
                    {"object-fit", nil},
                    {"object-position", nil},
                    {"overflow", nil},
                    {"overflow-x", nil},
                    {"overflow-y", nil},
                    {"overscroll", nil},
                    {"overscroll-x", nil},
                    {"overscroll-y", nil},
                    {"position", nil},
                    {"inset", nil},
                    {"inset-x", nil},
                    {"inset-y", nil},
                    {"start", nil},
                    {"end", nil},
                    {"inset-bs", nil},
                    {"inset-be", nil},
                    {"top", nil},
                    {"right", nil},
                    {"bottom", nil},
                    {"left", nil},
                    {"visibility", nil},
                    {"z", nil},
                    {"basis", nil},
                    {"flex-direction", nil},
                    {"flex-wrap", nil},
                    {"flex", nil},
                    {"grow", nil},
                    {"shrink", nil},
                    {"order", nil},
                    {"grid-cols", nil},
                    {"col-start-end", nil},
                    {"col-start", nil},
                    {"col-end", nil},
                    {"grid-rows", nil},
                    {"row-start-end", nil},
                    {"row-start", nil},
                    {"row-end", nil},
                    {"grid-flow", nil},
                    {"auto-cols", nil},
                    {"auto-rows", nil},
                    {"gap", :spacing},
                    {"gap-x", :spacing},
                    {"gap-y", :spacing},
                    {"justify-content", nil},
                    {"justify-items", nil},
                    {"justify-self", nil},
                    {"align-content", nil},
                    {"align-items", nil},
                    {"align-self", nil},
                    {"place-content", nil},
                    {"place-items", nil},
                    {"place-self", nil},
                    {"p", :spacing},
                    {"px", :spacing},
                    {"py", :spacing},
                    {"ps", :spacing},
                    {"pe", :spacing},
                    {"pbs", :spacing},
                    {"pbe", :spacing},
                    {"pt", :spacing},
                    {"pr", :spacing},
                    {"pb", :spacing},
                    {"pl", :spacing},
                    {"m", nil},
                    {"mx", nil},
                    {"my", nil},
                    {"ms", nil},
                    {"me", nil},
                    {"mbs", nil},
                    {"mbe", nil},
                    {"mt", nil},
                    {"mr", nil},
                    {"mb", nil},
                    {"ml", nil},
                    {"space-x", :spacing},
                    {"space-x-reverse", :spacing},
                    {"space-y", :spacing},
                    {"space-y-reverse", :spacing},
                    {"size", nil},
                    {"inline-size", nil},
                    {"min-inline-size", nil},
                    {"max-inline-size", nil},
                    {"block-size", nil},
                    {"min-block-size", nil},
                    {"max-block-size", nil},
                    {"w", nil},
                    {"min-w", nil},
                    {"max-w", nil},
                    {"h", nil},
                    {"min-h", nil},
                    {"max-h", nil},
                    {"font-size", :typography},
                    {"font-smoothing", :typography},
                    {"font-style", :typography},
                    {"font-weight", :typography},
                    {"font-stretch", :typography},
                    {"font-family", :typography},
                    {"font-features", :typography},
                    {"fvn-normal", :typography},
                    {"fvn-ordinal", :typography},
                    {"fvn-slashed-zero", :typography},
                    {"fvn-figure", :typography},
                    {"fvn-spacing", :typography},
                    {"fvn-fraction", :typography},
                    {"tracking", :typography},
                    {"line-clamp", :typography},
                    {"leading", :typography},
                    {"list-image", :typography},
                    {"list-style-position", :typography},
                    {"list-style-type", :typography},
                    {"text-alignment", nil},
                    {"placeholder-color", :color},
                    {"text-color", :color},
                    {"text-decoration", :typography},
                    {"text-decoration-style", :typography},
                    {"text-decoration-thickness", :typography},
                    {"text-decoration-color", :color},
                    {"underline-offset", :typography},
                    {"text-transform", :typography},
                    {"text-overflow", :typography},
                    {"text-wrap", :typography},
                    {"indent", :typography},
                    {"tab-size", nil},
                    {"vertical-align", nil},
                    {"whitespace", nil},
                    {"break", nil},
                    {"wrap", nil},
                    {"hyphens", :typography},
                    {"content", nil},
                    {"bg-attachment", :effects},
                    {"bg-clip", :effects},
                    {"bg-origin", :effects},
                    {"bg-position", :effects},
                    {"bg-repeat", :effects},
                    {"bg-size", :effects},
                    {"bg-image", :effects},
                    {"bg-color", :color},
                    {"gradient-from-pos", :effects},
                    {"gradient-via-pos", :effects},
                    {"gradient-to-pos", :effects},
                    {"gradient-from", :color},
                    {"gradient-via", :color},
                    {"gradient-to", :color},
                    {"rounded", :shape},
                    {"rounded-s", :shape},
                    {"rounded-e", :shape},
                    {"rounded-t", :shape},
                    {"rounded-r", :shape},
                    {"rounded-b", :shape},
                    {"rounded-l", :shape},
                    {"rounded-ss", :shape},
                    {"rounded-se", :shape},
                    {"rounded-ee", :shape},
                    {"rounded-es", :shape},
                    {"rounded-tl", :shape},
                    {"rounded-tr", :shape},
                    {"rounded-br", :shape},
                    {"rounded-bl", :shape},
                    {"border-w", :shape},
                    {"border-w-x", :shape},
                    {"border-w-y", :shape},
                    {"border-w-s", :shape},
                    {"border-w-e", :shape},
                    {"border-w-bs", :shape},
                    {"border-w-be", :shape},
                    {"border-w-t", :shape},
                    {"border-w-r", :shape},
                    {"border-w-b", :shape},
                    {"border-w-l", :shape},
                    {"divide-x", :shape},
                    {"divide-x-reverse", :shape},
                    {"divide-y", :shape},
                    {"divide-y-reverse", :shape},
                    {"border-style", :shape},
                    {"divide-style", :shape},
                    {"border-color", :color},
                    {"border-color-x", :color},
                    {"border-color-y", :color},
                    {"border-color-s", :color},
                    {"border-color-e", :color},
                    {"border-color-bs", :color},
                    {"border-color-be", :color},
                    {"border-color-t", :color},
                    {"border-color-r", :color},
                    {"border-color-b", :color},
                    {"border-color-l", :color},
                    {"divide-color", :color},
                    {"outline-style", :shape},
                    {"outline-offset", :shape},
                    {"outline-w", :shape},
                    {"outline-color", :color},
                    {"shadow", :effects},
                    {"shadow-color", :color},
                    {"inset-shadow", :effects},
                    {"inset-shadow-color", :color},
                    {"ring-w", :shape},
                    {"ring-w-inset", :shape},
                    {"ring-color", :color},
                    {"ring-offset-w", :shape},
                    {"ring-offset-color", :color},
                    {"inset-ring-w", :shape},
                    {"inset-ring-color", :color},
                    {"text-shadow", :effects},
                    {"text-shadow-color", :color},
                    {"opacity", :effects},
                    {"mix-blend", :effects},
                    {"bg-blend", :effects},
                    {"mask-clip", :effects},
                    {"mask-composite", :effects},
                    {"mask-image-linear-pos", :effects},
                    {"mask-image-linear-from-pos", :effects},
                    {"mask-image-linear-to-pos", :effects},
                    {"mask-image-linear-from-color", :color},
                    {"mask-image-linear-to-color", :color},
                    {"mask-image-t-from-pos", :effects},
                    {"mask-image-t-to-pos", :effects},
                    {"mask-image-t-from-color", :color},
                    {"mask-image-t-to-color", :color},
                    {"mask-image-r-from-pos", :effects},
                    {"mask-image-r-to-pos", :effects},
                    {"mask-image-r-from-color", :color},
                    {"mask-image-r-to-color", :color},
                    {"mask-image-b-from-pos", :effects},
                    {"mask-image-b-to-pos", :effects},
                    {"mask-image-b-from-color", :color},
                    {"mask-image-b-to-color", :color},
                    {"mask-image-l-from-pos", :effects},
                    {"mask-image-l-to-pos", :effects},
                    {"mask-image-l-from-color", :color},
                    {"mask-image-l-to-color", :color},
                    {"mask-image-x-from-pos", :effects},
                    {"mask-image-x-to-pos", :effects},
                    {"mask-image-x-from-color", :color},
                    {"mask-image-x-to-color", :color},
                    {"mask-image-y-from-pos", :effects},
                    {"mask-image-y-to-pos", :effects},
                    {"mask-image-y-from-color", :color},
                    {"mask-image-y-to-color", :color},
                    {"mask-image-radial", :effects},
                    {"mask-image-radial-from-pos", :effects},
                    {"mask-image-radial-to-pos", :effects},
                    {"mask-image-radial-from-color", :color},
                    {"mask-image-radial-to-color", :color},
                    {"mask-image-radial-shape", :effects},
                    {"mask-image-radial-size", :effects},
                    {"mask-image-radial-pos", :effects},
                    {"mask-image-conic-pos", :effects},
                    {"mask-image-conic-from-pos", :effects},
                    {"mask-image-conic-to-pos", :effects},
                    {"mask-image-conic-from-color", :color},
                    {"mask-image-conic-to-color", :color},
                    {"mask-mode", :effects},
                    {"mask-origin", :effects},
                    {"mask-position", :effects},
                    {"mask-repeat", :effects},
                    {"mask-size", :effects},
                    {"mask-type", :effects},
                    {"mask-image", :effects},
                    {"filter", :effects},
                    {"blur", :effects},
                    {"brightness", :effects},
                    {"contrast", :effects},
                    {"drop-shadow", :effects},
                    {"drop-shadow-color", :color},
                    {"grayscale", :effects},
                    {"hue-rotate", :effects},
                    {"invert", :effects},
                    {"saturate", :effects},
                    {"sepia", :effects},
                    {"backdrop-filter", :effects},
                    {"backdrop-blur", :effects},
                    {"backdrop-brightness", :effects},
                    {"backdrop-contrast", :effects},
                    {"backdrop-grayscale", :effects},
                    {"backdrop-hue-rotate", :effects},
                    {"backdrop-invert", :effects},
                    {"backdrop-opacity", :effects},
                    {"backdrop-saturate", :effects},
                    {"backdrop-sepia", :effects},
                    {"border-collapse", nil},
                    {"border-spacing", :spacing},
                    {"border-spacing-x", :spacing},
                    {"border-spacing-y", :spacing},
                    {"table-layout", nil},
                    {"caption", nil},
                    {"transition", :motion},
                    {"transition-behavior", :motion},
                    {"duration", :motion},
                    {"ease", :motion},
                    {"delay", :motion},
                    {"animate", :motion},
                    {"backface", nil},
                    {"perspective", nil},
                    {"perspective-origin", nil},
                    {"rotate", nil},
                    {"rotate-x", nil},
                    {"rotate-y", nil},
                    {"rotate-z", nil},
                    {"scale", nil},
                    {"scale-x", nil},
                    {"scale-y", nil},
                    {"scale-z", nil},
                    {"scale-3d", nil},
                    {"skew", nil},
                    {"skew-x", nil},
                    {"skew-y", nil},
                    {"transform", nil},
                    {"transform-origin", nil},
                    {"transform-style", nil},
                    {"translate", nil},
                    {"translate-x", nil},
                    {"translate-y", nil},
                    {"translate-z", nil},
                    {"translate-none", nil},
                    {"zoom", nil},
                    {"accent", :color},
                    {"appearance", nil},
                    {"caret-color", :color},
                    {"color-scheme", nil},
                    {"cursor", nil},
                    {"field-sizing", nil},
                    {"pointer-events", nil},
                    {"resize", nil},
                    {"scroll-behavior", nil},
                    {"scrollbar-thumb-color", :color},
                    {"scrollbar-track-color", :color},
                    {"scrollbar-gutter", nil},
                    {"scrollbar-w", nil},
                    {"scroll-m", nil},
                    {"scroll-mx", nil},
                    {"scroll-my", nil},
                    {"scroll-ms", nil},
                    {"scroll-me", nil},
                    {"scroll-mbs", nil},
                    {"scroll-mbe", nil},
                    {"scroll-mt", nil},
                    {"scroll-mr", nil},
                    {"scroll-mb", nil},
                    {"scroll-ml", nil},
                    {"scroll-p", nil},
                    {"scroll-px", nil},
                    {"scroll-py", nil},
                    {"scroll-ps", nil},
                    {"scroll-pe", nil},
                    {"scroll-pbs", nil},
                    {"scroll-pbe", nil},
                    {"scroll-pt", nil},
                    {"scroll-pr", nil},
                    {"scroll-pb", nil},
                    {"scroll-pl", nil},
                    {"snap-align", nil},
                    {"snap-stop", nil},
                    {"snap-type", nil},
                    {"snap-strictness", nil},
                    {"touch", nil},
                    {"touch-x", nil},
                    {"touch-y", nil},
                    {"touch-pz", nil},
                    {"select", nil},
                    {"will-change", nil},
                    {"fill", :color},
                    {"stroke-w", :shape},
                    {"stroke", :color},
                    {"forced-color-adjust", nil}
                  ])

  # Arbitrary properties ([color:red]) are categorized by CSS property name,
  # first match winning, so a contract opening layout does not open a
  # property that paints.
  @arbitrary_property_rules [
    {~S"(?:^|-)color$|^(?:background|fill|stroke|--tw-(?:gradient-(?:from|via|to)|shadow-color|ring-color|inset-ring-color|inset-shadow-color)|--tw-.*-color)$",
     "color"},
    {~S"^(?:padding|gap$|row-gap$|column-gap$)", "spacing"},
    {~S"^(?:font|letter-spacing$|line-height$|text-decoration|text-transform$|text-indent$|text-underline|word-spacing$|list-style)",
     "typography"},
    {~S"^(?:border(?:-(?:top|right|bottom|left|inline|block)(?:-(?:start|end))?)?(?:-(?:width|style|radius))?$|border-.*-radius$|outline|--tw-ring-width$|--tw-ring-inset$)",
     "shape"},
    {~S"^(?:box-shadow|text-shadow|opacity|filter|backdrop-filter|mix-blend-mode|background-blend-mode|--tw-(?:shadow|inset-shadow|drop-shadow|blur|brightness|contrast|grayscale|hue-rotate|invert|saturate|sepia|backdrop-.*)$)",
     "effects"},
    {~S"^(?:transition|animation|--tw-(?:duration|ease|delay)$)", "motion"}
  ]

  @arbitrary_prefix "arbitrary.."

  @doc "The appearance categories. `layout` is everything else."
  @spec categories() :: [String.t()]
  def categories, do: @categories

  @doc "Whether the grammar maps `group` to a category (or to layout)."
  @spec known_group?(String.t()) :: boolean()
  def known_group?(group), do: Map.has_key?(@group_category, group)

  @doc """
  The category of a class group, or `nil` for layout (and for no group).

      iex> HeexLint.Grammar.Categories.category_of("p")
      "spacing"
      iex> HeexLint.Grammar.Categories.category_of("mt")
      nil
      iex> HeexLint.Grammar.Categories.category_of("arbitrary..background-color")
      "color"
  """
  @spec category_of(String.t() | nil) :: String.t() | nil
  def category_of(nil), do: nil

  def category_of(@arbitrary_prefix <> property) do
    Enum.find_value(@arbitrary_property_rules, fn {pattern, category} ->
      if Regex.match?(Regex.compile!(pattern), property), do: category
    end)
  end

  def category_of(group) do
    case Map.get(@group_category, group) do
      nil -> nil
      category -> Atom.to_string(category)
    end
  end
end
